version: '2.1'

services:
#  app:
#    container_name: produx_app
#    build:
#      dockerfile: Dockerfile
#      context: ./docker
#    ports:
#      - "50000:50000"
#    restart: on-failure
#    networks:
#      - default
#    volumes:
#      - ./src:/app
#      - ./docker:/app/docker
#    env_file:
#      - .env
#    depends_on:
#      neo4j:
#        condition: service_healthy

  neo4j:
    container_name: produx_neo4j
#    image: bitnami/neo4j:latest
#    image: thetallgrassnet/alpine-neo4j
    image: neo4j/neo4j-arm64-experimental:4.1.0-arm64
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
    volumes:
      - ./neo4j_data:/data
#      - ./neo4j_data:/var/lib/neo4j/data
    env_file:
      - .env
    networks:
      - default
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:7474/"]
#      timeout: 10s
#      retries: 10

networks:
  default:
